"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Domain(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Domain._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Substr: Domain._Type.ValueType  # 0
        """The value is used as a sub string."""
        Regex: Domain._Type.ValueType  # 1
        """The value is used as a regular expression."""
        Domain: Domain._Type.ValueType  # 2
        """The value is a domain."""
        Full: Domain._Type.ValueType  # 3
        """The value is a full domain."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Type of domain value."""

    Substr: Domain.Type.ValueType  # 0
    """The value is used as a sub string."""
    Regex: Domain.Type.ValueType  # 1
    """The value is used as a regular expression."""
    Domain: Domain.Type.ValueType  # 2
    """The value is a domain."""
    Full: Domain.Type.ValueType  # 3
    """The value is a full domain."""

    @_typing.final
    class Attribute(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        BOOL_VALUE_FIELD_NUMBER: _builtins.int
        INT_VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        bool_value: _builtins.bool
        int_value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            bool_value: _builtins.bool = ...,
            int_value: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "int_value", b"int_value", "typed_value", b"typed_value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "int_value", b"int_value", "key", b"key", "typed_value", b"typed_value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_typed_value: _TypeAlias = _typing.Literal["bool_value", "int_value"]  # noqa: Y015
        _WhichOneofArgType_typed_value: _TypeAlias = _typing.Literal["typed_value", b"typed_value"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_typed_value) -> _WhichOneofReturnType_typed_value | None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_FIELD_NUMBER: _builtins.int
    type: Global___Domain.Type.ValueType
    """Domain matching type."""
    value: _builtins.str
    """Domain value."""
    @_builtins.property
    def attribute(self) -> _containers.RepeatedCompositeFieldContainer[Global___Domain.Attribute]:
        """Attributes of this domain. May be used for filtering."""

    def __init__(
        self,
        *,
        type: Global___Domain.Type.ValueType = ...,
        value: _builtins.str = ...,
        attribute: _abc.Iterable[Global___Domain.Attribute] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute", b"attribute", "type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Domain: _TypeAlias = Domain  # noqa: Y015

@_typing.final
class GeoSite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    @_builtins.property
    def domain(self) -> _containers.RepeatedCompositeFieldContainer[Global___Domain]: ...
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        domain: _abc.Iterable[Global___Domain] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "domain", b"domain"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoSite: _TypeAlias = GeoSite  # noqa: Y015

@_typing.final
class GeoSiteList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoSite]: ...
    def __init__(
        self,
        *,
        entry: _abc.Iterable[Global___GeoSite] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoSiteList: _TypeAlias = GeoSiteList  # noqa: Y015

@_typing.final
class GeoSiteRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    ATTRS_FIELD_NUMBER: _builtins.int
    file: _builtins.str
    code: _builtins.str
    attrs: _builtins.str
    def __init__(
        self,
        *,
        file: _builtins.str = ...,
        code: _builtins.str = ...,
        attrs: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attrs", b"attrs", "code", b"code", "file", b"file"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoSiteRule: _TypeAlias = GeoSiteRule  # noqa: Y015

@_typing.final
class DomainRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GEOSITE_FIELD_NUMBER: _builtins.int
    CUSTOM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def geosite(self) -> Global___GeoSiteRule: ...
    @_builtins.property
    def custom(self) -> Global___Domain: ...
    def __init__(
        self,
        *,
        geosite: Global___GeoSiteRule | None = ...,
        custom: Global___Domain | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["custom", b"custom", "geosite", b"geosite", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["custom", b"custom", "geosite", b"geosite", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["geosite", "custom"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___DomainRule: _TypeAlias = DomainRule  # noqa: Y015

@_typing.final
class CIDR(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IP_FIELD_NUMBER: _builtins.int
    PREFIX_FIELD_NUMBER: _builtins.int
    ip: _builtins.bytes
    """IP address, should be either 4 or 16 bytes."""
    prefix: _builtins.int
    """Number of leading ones in the network mask."""
    def __init__(
        self,
        *,
        ip: _builtins.bytes = ...,
        prefix: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ip", b"ip", "prefix", b"prefix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CIDR: _TypeAlias = CIDR  # noqa: Y015

@_typing.final
class CIDRRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CIDR_FIELD_NUMBER: _builtins.int
    REVERSE_MATCH_FIELD_NUMBER: _builtins.int
    reverse_match: _builtins.bool
    @_builtins.property
    def cidr(self) -> Global___CIDR: ...
    def __init__(
        self,
        *,
        cidr: Global___CIDR | None = ...,
        reverse_match: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cidr", b"cidr"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cidr", b"cidr", "reverse_match", b"reverse_match"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CIDRRule: _TypeAlias = CIDRRule  # noqa: Y015

@_typing.final
class GeoIP(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    CIDR_FIELD_NUMBER: _builtins.int
    REVERSE_MATCH_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    reverse_match: _builtins.bool
    @_builtins.property
    def cidr(self) -> _containers.RepeatedCompositeFieldContainer[Global___CIDR]: ...
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        cidr: _abc.Iterable[Global___CIDR] | None = ...,
        reverse_match: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cidr", b"cidr", "code", b"code", "reverse_match", b"reverse_match"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoIP: _TypeAlias = GeoIP  # noqa: Y015

@_typing.final
class GeoIPList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoIP]: ...
    def __init__(
        self,
        *,
        entry: _abc.Iterable[Global___GeoIP] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoIPList: _TypeAlias = GeoIPList  # noqa: Y015

@_typing.final
class GeoIPRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    REVERSE_MATCH_FIELD_NUMBER: _builtins.int
    file: _builtins.str
    code: _builtins.str
    reverse_match: _builtins.bool
    def __init__(
        self,
        *,
        file: _builtins.str = ...,
        code: _builtins.str = ...,
        reverse_match: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "file", b"file", "reverse_match", b"reverse_match"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoIPRule: _TypeAlias = GeoIPRule  # noqa: Y015

@_typing.final
class IPRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GEOIP_FIELD_NUMBER: _builtins.int
    CUSTOM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def geoip(self) -> Global___GeoIPRule: ...
    @_builtins.property
    def custom(self) -> Global___CIDRRule: ...
    def __init__(
        self,
        *,
        geoip: Global___GeoIPRule | None = ...,
        custom: Global___CIDRRule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["custom", b"custom", "geoip", b"geoip", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["custom", b"custom", "geoip", b"geoip", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["geoip", "custom"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___IPRule: _TypeAlias = IPRule  # noqa: Y015