export interface RoutingValidationError {
  path: string
  message: string
}

export interface RoutingValidationResult {
  valid: boolean
  errors: RoutingValidationError[]
  warnings: RoutingValidationError[]
}

export function validateRoutingJson(json: string): RoutingValidationResult {
  const errors: RoutingValidationError[] = []
  const warnings: RoutingValidationError[] = []

  if (!json.trim()) {
    return { valid: false, errors: [{ path: '', message: 'Config is empty' }], warnings }
  }

  let doc: unknown
  try {
    doc = JSON.parse(json)
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : 'Invalid JSON'
    errors.push({ path: '', message: `Invalid JSON — ${msg}` })
    return { valid: false, errors, warnings }
  }

  if (!doc || typeof doc !== 'object' || Array.isArray(doc)) {
    errors.push({ path: '', message: 'JSON root must be an object' })
    return { valid: false, errors, warnings }
  }

  const root = doc as Record<string, unknown>

  const routing = root.routing as Record<string, unknown> | undefined
  const rules = routing?.rules
  if (!Array.isArray(rules) || rules.length === 0) {
    errors.push({ path: 'routing.rules', message: 'must contain at least one rule' })
  }

  const outbounds = root.outbounds
  if (!Array.isArray(outbounds) || outbounds.length === 0) {
    errors.push({ path: 'outbounds', message: 'must contain at least one outbound' })
  }

  if ('dns' in root) {
    warnings.push({ path: 'dns', message: 'will be ignored (generated by OLCWave)' })
  }

  if ('inbounds' in root) {
    warnings.push({ path: 'inbounds', message: 'will be ignored (generated by OLCWave)' })
  }

  return { valid: errors.length === 0, errors, warnings }
}

export function stripRoutingFields(json: string): string {
  const doc = JSON.parse(json) as Record<string, unknown>
  delete doc.dns
  delete doc.inbounds
  return JSON.stringify(doc, null, 2)
}
